import "./globals.css";
import Navbar from "../../components/Navbar";
import SessionWrapper from "../../components/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
